-- Migration: IoT device refactor & add sensor_readings
-- Description: Drop unused columns from edge_nodes and devices, make room_id mandatory, and create sensor_readings table.

-- 1. Modify edge_nodes table
ALTER TABLE edge_nodes DROP COLUMN IF EXISTS mac_address;
ALTER TABLE edge_nodes DROP COLUMN IF EXISTS ip_address;
ALTER TABLE edge_nodes DROP COLUMN IF EXISTS firmware_version;
ALTER TABLE edge_nodes DROP COLUMN IF EXISTS last_ack_at;

-- 2. Modify devices table
-- Drop foreign key to homes (assuming default constraint name generated by postgres)
ALTER TABLE devices DROP CONSTRAINT IF EXISTS devices_home_id_fkey;

-- Drop unique constraint on node_id and gpio_pin
ALTER TABLE devices DROP CONSTRAINT IF EXISTS devices_node_id_gpio_pin_key;

-- Drop columns
ALTER TABLE devices DROP COLUMN IF EXISTS home_id;
ALTER TABLE devices DROP COLUMN IF EXISTS gpio_pin;
ALTER TABLE devices DROP COLUMN IF EXISTS last_seen;

-- Make room_id NOT NULL (Caution: may fail if there are existing records with NULL room_id)
-- If this fails on existing data, you may need to assign them to a default room first.
ALTER TABLE devices ALTER COLUMN room_id SET NOT NULL;

-- 3. Create sensor_readings table
CREATE TABLE IF NOT EXISTS sensor_readings (
    id BIGSERIAL PRIMARY KEY,
    device_id UUID NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    metric_type VARCHAR(50) NOT NULL,
    value NUMERIC(15,4) NOT NULL,
    unit VARCHAR(20) NOT NULL,
    recorded_at TIMESTAMPTZ NOT NULL
);

-- Create index for faster time-series queries
CREATE INDEX IF NOT EXISTS idx_sensor_readings_device_time ON sensor_readings(device_id, recorded_at);
